# Site settings
title: Modern Bedouin
email: contact@modernbedou.in
description: "A blog about life, liberty, and the pursuit of technology."
baseurl: ""
url: "http://modernbedou.in"
twitter_username: jamilbk
github_username:  jamilbk

# Build settings
markdown: kramdown
permalink: pretty
