# Site settings
title: modern bedouin
email: "&#099;&#111;&#110;&#116;&#097;&#099;&#116;&#064;&#109;&#111;&#100;&#101;&#114;&#110;&#098;&#101;&#100;&#111;&#117;&#046;&#105;&#110;"
description: "Life, liberty, and the pursuit of technology."
baseurl: ""
url: "http://modernbedou.in"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
