# Site settings
title: modern bedouin
email: contact@modernbedou.in
description: "Life, liberty, and the pursuit of technology."
baseurl: ""
url: "http://modernbedou.in"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
